server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: clients-api
          uri: lb://clients-api
          predicates:
            - Path=/v1/clients/**
        - id: books-api
          uri: lb://books-api
          predicates:
            - Path=/v1/books/**
        - id: purchases-api
          uri: lb://purchases-api
          predicates:
            - Path=/v1/purchases/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG