server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: clients-api
          uri: http://localhost:8081/v1/clients
          predicates:
            - Path=/v1/clients/**
        - id: books-api
          uri: http://localhost:8082/v1/books
          predicates:
            - Path=/v1/books/**
        - id: purchases-api
          uri: http://localhost:8080/v1/purchases
          predicates:
            - Path=/v1/purchases/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG